spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  header: Authorization
  #  multiply-spring-boot-security-jwt-secret-multiply-spring-boot-security-jwt-secret
  secret: bXVsdGlwbHktc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1tdWx0aXBseS1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2VjcmV0
  #  token-validity-in-seconds: 60000  # 1분
  token-validity-in-seconds: 43200000

# Dev test
encrypt:
  key: 6258567364476C7762486B3D

server:
  tomcat:
    max-http-form-post-size: 10MB